#!/bin/bash

# ────────────────────────────────────────────────
#   First Boot Setup Script - Hostname + Static IP
# ────────────────────────────────────────────────

set -e
set -o pipefail

# ── Banner ───────────────────────────────────────
echo "╔══════════════════════════════════════════════════╗"
echo "║   🛠  Hostname & Static IP Configuration Script   ║"
echo "╚══════════════════════════════════════════════════╝"
echo

# ── 1. System Update ─────────────────────────────
echo "📦 Updating package lists and upgrading packages..."
sudo apt update -y && sudo apt upgrade -y
echo "✅ System updated."
echo

# ── 2. Hostname Configuration ────────────────────
read -p "👉 Enter the new hostname: " NEW_HOSTNAME

if [ -z "$NEW_HOSTNAME" ]; then
    echo "❌ No hostname provided. Exiting."
    exit 1
fi

echo "🔧 Setting hostname to: $NEW_HOSTNAME"
sudo hostnamectl set-hostname "$NEW_HOSTNAME"

# Update /etc/hosts (only the 127.0.0.1 line)
sudo sed -i "s/^127\.0\.0\.1.*/127.0.0.1 localhost $NEW_HOSTNAME/" /etc/hosts

echo "✅ Hostname successfully updated to: $(hostname)"
echo

# ── 3. Detect Network Settings ───────────────────
echo "🌐 Detecting network settings..."
IFACE=$(ip -o -4 route show to default | awk '{print $5}')
IP_CIDR=$(ip -o -4 addr show "$IFACE" | awk '{print $4}')
IP_ADDR=$(echo "$IP_CIDR" | cut -d/ -f1)
SUBNET_MASK=$(echo "$IP_CIDR" | cut -d/ -f2)
GATEWAY=$(ip route | grep default | awk '{print $3}')

if [ -z "$IFACE" ] || [ -z "$IP_ADDR" ] || [ -z "$GATEWAY" ]; then
    echo "❌ Failed to detect network settings. Exiting."
    exit 1
fi

echo "📡 Interface: $IFACE"
echo "📌 IP: $IP_ADDR/$SUBNET_MASK  |  Gateway: $GATEWAY"
echo

# ── 4. Backup Interfaces File ────────────────────
echo "📝 Backing up /etc/network/interfaces..."
sudo cp /etc/network/interfaces /etc/network/interfaces.bak.$(date +%F_%H-%M-%S)
echo "✅ Backup created."
echo

# ── 5. Configure Static IP ───────────────────────
echo "🛠 Applying static IP configuration..."
sudo tee /etc/network/interfaces > /dev/null <<EOL
# Autogenerated by setup script
auto lo
iface lo inet loopback

auto $IFACE
iface $IFACE inet static
    address $IP_ADDR
    netmask $SUBNET_MASK
    gateway $GATEWAY
EOL

# ── 6. Restart Networking ────────────────────────
echo "🔄 Restarting networking service..."
if sudo systemctl restart networking; then
    echo "✅ Static IP applied: $IP_ADDR"
else
    echo "❌ Failed to restart networking."
    exit 1
fi

echo
echo "🎉 All done!"
echo "   • Hostname: $NEW_HOSTNAME"
echo "   • Static IP: $IP_ADDR"
echo
echo "👉 Tip: Reconnect your SSH session to see the new hostname in the prompt."
