#!/bin/bash

# 1. Determine the network interface (e.g., 'eth0' or 'eno1')
IFACE=$(ip -o -4 route show to default | awk '{print $5}')

# 2. Get the current IP address, subnet mask, and default gateway
IP_ADDR=$(ip -o -4 addr show $IFACE | awk '{print $4}' | cut -d/ -f1)
SUBNET_MASK=$(ip -o -4 addr show $IFACE | awk '{print $4}' | cut -d/ -f2)
GATEWAY=$(ip route | grep default | awk '{print $3}')

# 3. Validate the values to ensure they are not empty
if [ -z "$IP_ADDR" ] || [ -z "$SUBNET_MASK" ] || [ -z "$GATEWAY" ]; then
  echo "Error: Could not retrieve network settings. Exiting."
  exit 1
fi

# 4. Backup the /etc/network/interfaces file
cp /etc/network/interfaces /etc/network/interfaces.bak

# 5. Update the interfaces file with the static IP configuration
cat <<EOL > /etc/network/interfaces
# This file is autogenerated by script
auto $IFACE
iface $IFACE inet static
    address $IP_ADDR
    netmask $SUBNET_MASK
    gateway $GATEWAY
EOL

# 6. Restart the networking service
if systemctl restart networking; then
  echo "The network interface is now using a static IP: $IP_ADDR"
else
  echo "Error: Failed to restart the networking service."
  exit 1
fi
